version: "3"
services:
  web:
    image: ${PROJET_NAME}-nodejs-v${NODEJS}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODEJS}
        - HTTP_PORT=${HTTP_CONTAINER}
        - HTTPS_PORT=${HTTPS_CONTAINER}
    container_name: ${PROJET_NAME}__${APP_CONTAINER_NAME}
    ports:
      - "${HTTP_LOCAL}:${HTTP_CONTAINER}"
      - "${HTTPS_LOCAL}:${HTTPS_CONTAINER}"
    volumes:
      - ./:/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      meanstack_net:
        ipv4_address: ${APP_IP}
    tty: true

  mongo-express:
    image: mongo-express
    restart: always
    container_name: ${PROJET_NAME}__${DBVIEWER_CONTAINER_NAME}
    ports:
      - "${MONGO_EXPRESS_LOCAL}:${MONGO_EXPRESS_CONTAINER}"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGODB_LOCAL}
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: mongomed
    networks:
      meanstack_net:
        ipv4_address: ${DBVIEWER_IP}

  mongo:
    image: mongo
    restart: always
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: mongomed
    container_name: ${PROJET_NAME}__${DB_CONTAINER_NAME}
    ports:
      - "${MONGODB_LOCAL}:${MONGODB_CONTAINER}"
    volumes:
      - ./infrastructure/mongodata:/data/db
    networks:
      meanstack_net:
        ipv4_address: ${DB_IP}

networks:
  meanstack_net:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
