version: "3"
services:
  web:
    image: node${NODEJS}expressjs
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODEJS}
        - HTTP_PORT=${HTTP_CONTAINER}
        - HTTPS_PORT=${HTTPS_CONTAINER}
        - KARMA_PORT=${KARMA_CONTAINER}
    container_name: ${CONTAINER_NAME}
    ports:
      - "${HTTP_LOCAL}:${HTTP_CONTAINER}"
      - "${HTTPS_LOCAL}:${HTTPS_CONTAINER}"
      - "${KARMA_LOCAL}:${KARMA_CONTAINER}"
    volumes:
      - ./:/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    tty: true

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: med
      ME_CONFIG_BASICAUTH_PASSWORD: mongomed
      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongomed
    links:
      - mongo

  mongo:
    image: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: mongomed
    ports:
      - "27017:27017"
